
apiVersion: batch/v1
kind: Job
metadata:
  name: 59022c1
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: 59022c1
        image: devopsbasservice/springpetclinic:59022c1
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
      restartPolicy: Never

